[package]
name = "powergrid_token"
version = "0.1.0"
authors = ["Kunal <kunaldrall29@gmail.com>", "Daksh"]
edition = "2021"

[dependencies]
ink.workspace = true
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2.11", default-features = false, features = ["derive"] }
powergrid-shared = { path = "../../shared", default-features = false }

[dev-dependencies]
ink_e2e.workspace = true

[lib]
path = "src/lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",
    "powergrid-shared/std",
]
ink-as-dependency = []
e2e-tests = []